# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_mainshow_shop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainshow',
            table='axf_mainshow',
        ),
        migrations.AlterModelTable(
            name='shop',
            table='axf_shop',
        ),
    ]
