# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='axf_user',
        ),
    ]
